### ISSUE TITLE
Изменить структуру проекта

### ISSUE THREAD

**Issue by BrBrRoman** [frontend-park-mail-ru/2019_1_qwerty#5]
Не создавать под каждую страницу отдельную папку, а делить файлы по расширениям.
Например так
![default](https://user-images.githubusercontent.com/32716489/53376463-70e94680-396f-11e9-83b2-e0ba293971a9.png)

**Comment by OkciD** [comment]
А зачем? Что не так с имеющейся архитектурой, где для каждого компонента своя папка?

**Comment by OkciD** [comment]
Нашёл ответ на свой вопрос в чатике:

> Roman, [27 февр. 2019 г., 0:03:42]:
Чтоб слить эти повторяющиеся и в чём-то по своему уникальные css в 1

> Roman, [27 февр. 2019 г., 0:05:31 (27.02.2019, 0:06:14)]:
Костя мне говорил, что вам на лекциях рассказывали о разделении всяких header'ов, footer'ов, sidebar'ов и т.п. в отдельные папки

> Roman, [27 февр. 2019 г., 0:05:58]:
но никак не подразумевалось, что каждая страница будет настолько автономна от других

Ваши страницы не будут автономны от друга. У вас вообще будет всего одна страница &ndash; в этом и суть SPA. Не надо менять архитектуру, ибо когда будете делать ДЗ2 (или сразу 3), вы будете вынуждены вернуть её обратно.
